/* GENERATED by compute_debtcontact.js — ห้ามแก้ไฟล์นี้ตรง แก้ที่ compute_debtcontact.js แล้ว gen ใหม่ */
/* base: debtcontact_base.pdf (13-08-2569) · A4 595.2x841.92 · 1 หน้า */
window.DEBTCONTACT_MAP = {
  "baseDY": -11,
  "docDate": {
    "page": 1,
    "x": 301.1,
    "y": 158.6,
    "size": 16,
    "max": 171,
    "cx": 386.6,
    "align": "center"
  },
  "name": {
    "page": 1,
    "x": 283,
    "y": 179.7,
    "size": 16,
    "max": 240,
    "cx": 403,
    "align": "center"
  },
  "house": {
    "page": 1,
    "x": 134.6,
    "y": 200.6,
    "size": 16,
    "max": 41,
    "cx": 155.1,
    "align": "center"
  },
  "moo": {
    "page": 1,
    "x": 211.9,
    "y": 200.6,
    "size": 16,
    "max": 33,
    "cx": 228.4,
    "align": "center"
  },
  "tambon": {
    "page": 1,
    "x": 278.9,
    "y": 200.6,
    "size": 16,
    "max": 127,
    "cx": 342.4,
    "align": "center"
  },
  "tel": {
    "page": 1,
    "x": 151.3,
    "y": 221.5,
    "size": 16,
    "max": 101,
    "cx": 201.8,
    "align": "center"
  },
  "p1Name": {
    "page": 1,
    "x": 192.9,
    "y": 389.2,
    "size": 16,
    "max": 204,
    "cx": 294.9,
    "align": "center"
  },
  "p1Rel": {
    "page": 1,
    "x": 458.3,
    "y": 389.2,
    "size": 16,
    "max": 64,
    "cx": 490.3,
    "align": "center"
  },
  "p1Addr": {
    "page": 1,
    "x": 130.8,
    "y": 411.8,
    "size": 16,
    "max": 269,
    "cx": 265.3,
    "align": "center"
  },
  "p1Tel": {
    "page": 1,
    "x": 442.5,
    "y": 411.8,
    "size": 16,
    "max": 80,
    "cx": 482.5,
    "align": "center"
  },
  "p2Name": {
    "page": 1,
    "x": 192.9,
    "y": 434.4,
    "size": 16,
    "max": 204,
    "cx": 294.9,
    "align": "center"
  },
  "p2Rel": {
    "page": 1,
    "x": 458.3,
    "y": 434.4,
    "size": 16,
    "max": 64,
    "cx": 490.3,
    "align": "center"
  },
  "p2Addr": {
    "page": 1,
    "x": 130.8,
    "y": 457.2,
    "size": 16,
    "max": 269,
    "cx": 265.3,
    "align": "center"
  },
  "p2Tel": {
    "page": 1,
    "x": 442.5,
    "y": 457.2,
    "size": 16,
    "max": 80,
    "cx": 482.5,
    "align": "center"
  },
  "p3Name": {
    "page": 1,
    "x": 192.9,
    "y": 479.7,
    "size": 16,
    "max": 204,
    "cx": 294.9,
    "align": "center"
  },
  "p3Rel": {
    "page": 1,
    "x": 458.3,
    "y": 479.7,
    "size": 16,
    "max": 64,
    "cx": 490.3,
    "align": "center"
  },
  "p3Addr": {
    "page": 1,
    "x": 130.8,
    "y": 502.3,
    "size": 16,
    "max": 269,
    "cx": 265.3,
    "align": "center"
  },
  "p3Tel": {
    "page": 1,
    "x": 442.5,
    "y": 502.3,
    "size": 16,
    "max": 80,
    "cx": 482.5,
    "align": "center"
  },
  "signGiver": {
    "page": 1,
    "x": 304.6,
    "y": 683.2,
    "size": 16,
    "max": 171,
    "cx": 390.1,
    "align": "center"
  },
  "signRecorder": {
    "page": 1,
    "x": 304.6,
    "y": 728.6,
    "size": 16,
    "max": 155,
    "cx": 382.1,
    "align": "center"
  },
  "signGiverName": {
    "page": 1,
    "x": 304.1,
    "y": 705.8,
    "size": 15,
    "max": 169,
    "cx": 388.6,
    "align": "center"
  },
  "signRecorderName": {
    "page": 1,
    "x": 304.1,
    "y": 751.2,
    "size": 15,
    "max": 169,
    "cx": 388.6,
    "align": "center"
  }
};
