/* GENERATED by compute_janong.js — ห้ามแก้ไฟล์นี้ตรง แก้ที่ compute_janong.js แล้ว gen ใหม่ */
/* base: janong_base.pdf (v2 20-07-2569) · A4 595.2x841.92 · 1 หน้า */
window.JANONG_MAP = {
  "baseDY": -11,
  "docDate": {
    "page": 1,
    "x": 356.1,
    "y": 107.9,
    "size": 16,
    "max": 197,
    "cx": 454.6,
    "align": "center"
  },
  "name": {
    "page": 1,
    "x": 134.6,
    "y": 165.3,
    "size": 16,
    "max": 282,
    "cx": 275.6,
    "align": "center"
  },
  "reg": {
    "page": 1,
    "x": 474,
    "y": 165.3,
    "size": 16,
    "max": 70,
    "cx": 509,
    "align": "center"
  },
  "group": {
    "page": 1,
    "x": 64.2,
    "y": 186.6,
    "size": 16,
    "max": 54,
    "cx": 91.2,
    "align": "center"
  },
  "amount": {
    "page": 1,
    "x": 284.7,
    "y": 186.6,
    "size": 16,
    "max": 132,
    "cx": 350.7,
    "align": "center"
  },
  "purpose1Amount": {
    "page": 1,
    "x": 163.4,
    "y": 229.1,
    "size": 16,
    "max": 90,
    "cx": 208.4,
    "align": "center"
  },
  "purpose1": {
    "page": 1,
    "x": 356.5,
    "y": 229.1,
    "size": 16,
    "max": 191,
    "cx": 452,
    "align": "center"
  },
  "purpose2Amount": {
    "page": 1,
    "x": 163.4,
    "y": 250.5,
    "size": 16,
    "max": 90,
    "cx": 208.4,
    "align": "center"
  },
  "purpose2": {
    "page": 1,
    "x": 356.5,
    "y": 250.5,
    "size": 16,
    "max": 191,
    "cx": 452,
    "align": "center"
  },
  "useOtherName": {
    "page": 1,
    "x": 392.5,
    "y": 328.9,
    "size": 15,
    "max": 153,
    "cx": 469,
    "align": "center"
  },
  "debtMidCount": {
    "page": 1,
    "x": 307.2,
    "y": 595.8,
    "size": 16,
    "max": 70,
    "cx": 342.2,
    "align": "center"
  },
  "debtMidAmount": {
    "page": 1,
    "x": 457.5,
    "y": 595.8,
    "size": 16,
    "max": 72,
    "cx": 493.5,
    "align": "center"
  },
  "debtShortCount": {
    "page": 1,
    "x": 279.4,
    "y": 617.2,
    "size": 16,
    "max": 96,
    "cx": 327.4,
    "align": "center"
  },
  "debtShortAmount": {
    "page": 1,
    "x": 457.5,
    "y": 617.2,
    "size": 16,
    "max": 72,
    "cx": 493.5,
    "align": "center"
  },
  "debtTradeCount": {
    "page": 1,
    "x": 297.5,
    "y": 638.5,
    "size": 16,
    "max": 77,
    "cx": 336,
    "align": "center"
  },
  "debtTradeAmount": {
    "page": 1,
    "x": 457.5,
    "y": 638.5,
    "size": 16,
    "max": 72,
    "cx": 493.5,
    "align": "center"
  },
  "debtOtherCount": {
    "page": 1,
    "x": 282.7,
    "y": 659.9,
    "size": 16,
    "max": 93,
    "cx": 329.2,
    "align": "center"
  },
  "debtOtherAmount": {
    "page": 1,
    "x": 457.5,
    "y": 659.9,
    "size": 16,
    "max": 72,
    "cx": 493.5,
    "align": "center"
  },
  "lateCount": {
    "page": 1,
    "x": 284,
    "y": 714.4,
    "size": 16,
    "max": 62,
    "cx": 315,
    "align": "center"
  },
  "onTimeCount": {
    "page": 1,
    "x": 467.2,
    "y": 714.4,
    "size": 16,
    "max": 67,
    "cx": 500.7,
    "align": "center"
  },
  "remark1": {
    "page": 1,
    "x": 204.8,
    "y": 741.7,
    "size": 16,
    "max": 347,
    "cx": 378.3,
    "align": "center"
  },
  "remark2": {
    "page": 1,
    "x": 116.5,
    "y": 762.9,
    "size": 16,
    "max": 433,
    "cx": 333,
    "align": "center"
  },
  "useSelf": {
    "page": 1,
    "cx": 219.7,
    "y": 325,
    "dy": 9,
    "size": 13,
    "align": "center",
    "tick": true
  },
  "useOther": {
    "page": 1,
    "cx": 304.8,
    "y": 325,
    "dy": 9,
    "size": 13,
    "align": "center",
    "tick": true
  },
  "amtFit": {
    "page": 1,
    "cx": 333.1,
    "y": 352.4,
    "dy": 9,
    "size": 13,
    "align": "center",
    "tick": true
  },
  "amtUnfit": {
    "page": 1,
    "cx": 418.2,
    "y": 352.4,
    "dy": 9,
    "size": 13,
    "align": "center",
    "tick": true
  },
  "coopAlways": {
    "page": 1,
    "cx": 361.5,
    "y": 379.5,
    "dy": 9,
    "size": 13,
    "align": "center",
    "tick": true
  },
  "coopYes": {
    "page": 1,
    "cx": 121.6,
    "y": 400.8,
    "dy": 9,
    "size": 13,
    "align": "center",
    "tick": true
  },
  "coopNo": {
    "page": 1,
    "cx": 248.1,
    "y": 400.8,
    "dy": 9,
    "size": 13,
    "align": "center",
    "tick": true
  },
  "payOnTime": {
    "page": 1,
    "cx": 230.1,
    "y": 428.2,
    "dy": 9,
    "size": 13,
    "align": "center",
    "tick": true
  },
  "paySomeLate": {
    "page": 1,
    "cx": 333.1,
    "y": 428.2,
    "dy": 9,
    "size": 13,
    "align": "center",
    "tick": true
  },
  "payAlwaysLate": {
    "page": 1,
    "cx": 446.5,
    "y": 428.2,
    "dy": 9,
    "size": 13,
    "align": "center",
    "tick": true
  },
  "statusGood": {
    "page": 1,
    "cx": 276.4,
    "y": 455.6,
    "dy": 9,
    "size": 13,
    "align": "center",
    "tick": true
  },
  "statusFair": {
    "page": 1,
    "cx": 333.1,
    "y": 455.6,
    "dy": 9,
    "size": 13,
    "align": "center",
    "tick": true
  },
  "statusPoor": {
    "page": 1,
    "cx": 446.5,
    "y": 455.6,
    "dy": 9,
    "size": 13,
    "align": "center",
    "tick": true
  },
  "secureFirm": {
    "page": 1,
    "cx": 333.1,
    "y": 482.7,
    "dy": 9,
    "size": 13,
    "align": "center",
    "tick": true
  },
  "secureWeak": {
    "page": 1,
    "cx": 446.5,
    "y": 482.7,
    "dy": 9,
    "size": 13,
    "align": "center",
    "tick": true
  },
  "approveYes": {
    "page": 1,
    "cx": 276.4,
    "y": 510,
    "dy": 9,
    "size": 13,
    "align": "center",
    "tick": true
  },
  "approveLess": {
    "page": 1,
    "cx": 361.5,
    "y": 510,
    "dy": 9,
    "size": 13,
    "align": "center",
    "tick": true
  },
  "approveReject": {
    "page": 1,
    "cx": 474.9,
    "y": 510,
    "dy": 9,
    "size": 13,
    "align": "center",
    "tick": true
  },
  "collPerson": {
    "page": 1,
    "cx": 191.4,
    "y": 683.1,
    "dy": 9,
    "size": 13,
    "align": "center",
    "tick": true
  },
  "collProperty": {
    "page": 1,
    "cx": 276.4,
    "y": 683.1,
    "dy": 9,
    "size": 13,
    "align": "center",
    "tick": true
  },
  "collDeposit": {
    "page": 1,
    "cx": 389.8,
    "y": 683.1,
    "dy": 9,
    "size": 13,
    "align": "center",
    "tick": true
  },
  "collShare": {
    "page": 1,
    "cx": 474.9,
    "y": 683.1,
    "dy": 9,
    "size": 13,
    "align": "center",
    "tick": true
  }
};
window.JANONG_TICK_KEYS = ["useSelf","useOther","amtFit","amtUnfit","coopAlways","coopYes","coopNo","payOnTime","paySomeLate","payAlwaysLate","statusGood","statusFair","statusPoor","secureFirm","secureWeak","approveYes","approveLess","approveReject","collPerson","collProperty","collDeposit","collShare"];
