/* generated by compute_share.js — แก้พิกัด: แก้ที่สคริปต์นั้น แล้ว regen ห้ามแก้ไฟล์นี้ตรง */
window.SHARE_MAP = {
  "docDate": {
    "page": 1,
    "x": 385.6,
    "y": 167.3,
    "size": 16,
    "max": 139
  },
  "name": {
    "page": 1,
    "x": 177.2,
    "y": 215.2,
    "size": 16,
    "max": 173
  },
  "reg": {
    "page": 1,
    "x": 410.2,
    "y": 215.2,
    "size": 16,
    "max": 53
  },
  "group": {
    "page": 1,
    "x": 496.6,
    "y": 215.2,
    "size": 16,
    "max": 28
  },
  "house": {
    "page": 1,
    "x": 155.3,
    "y": 236.1,
    "size": 16,
    "max": 25
  },
  "moo": {
    "page": 1,
    "x": 203.6,
    "y": 236.1,
    "size": 16,
    "max": 15
  },
  "tambon": {
    "page": 1,
    "x": 245.8,
    "y": 236.1,
    "size": 16,
    "max": 133
  },
  "postcode": {
    "page": 1,
    "x": 139.8,
    "y": 257.1,
    "size": 16,
    "max": 97
  },
  "tel": {
    "page": 1,
    "x": 301.3,
    "y": 257.1,
    "size": 16,
    "max": 135
  },
  "loanRange": {
    "page": 1,
    "x": 490.9,
    "y": 301.9,
    "size": 16,
    "max": 33
  },
  "loanDate": {
    "page": 1,
    "x": 132,
    "y": 322.9,
    "size": 16,
    "max": 51
  },
  "amount": {
    "page": 1,
    "x": 230,
    "y": 322.9,
    "size": 16,
    "max": 74
  },
  "amountText": {
    "page": 1,
    "x": 329.9,
    "y": 322.9,
    "size": 15,
    "max": 185
  },
  "shares": {
    "page": 1,
    "x": 364.4,
    "y": 346.9,
    "size": 16,
    "max": 53
  },
  "shareBaht": {
    "page": 1,
    "x": 101.2,
    "y": 367.9,
    "size": 16,
    "max": 97
  },
  "shareBahtText": {
    "page": 1,
    "x": 225.3,
    "y": 367.9,
    "size": 15,
    "max": 207
  },
  "nameParen": {
    "page": 1,
    "cx": 419.8,
    "y": 595.5,
    "size": 16,
    "max": 167,
    "align": "center"
  },
  "baseDY": -11
};
