/* generated by compute_share.js — แก้พิกัด: แก้ที่สคริปต์นั้น แล้ว regen ห้ามแก้ไฟล์นี้ตรง */
window.SHARE_MAP = {
  "docDate": {
    "page": 1,
    "x": 385.3,
    "y": 167.2,
    "size": 16,
    "max": 139,
    "cx": 454.8,
    "align": "center"
  },
  "name": {
    "page": 1,
    "x": 177,
    "y": 215.2,
    "size": 16,
    "max": 173,
    "cx": 263.5,
    "align": "center"
  },
  "reg": {
    "page": 1,
    "x": 410.2,
    "y": 215.2,
    "size": 16,
    "max": 53,
    "cx": 436.7,
    "align": "center"
  },
  "group": {
    "page": 1,
    "x": 496.3,
    "y": 215.2,
    "size": 16,
    "max": 28,
    "cx": 510.3,
    "align": "center"
  },
  "house": {
    "page": 1,
    "x": 155.2,
    "y": 236.1,
    "size": 16,
    "max": 25,
    "cx": 167.7,
    "align": "center"
  },
  "moo": {
    "page": 1,
    "x": 203.5,
    "y": 236.1,
    "size": 16,
    "max": 15,
    "cx": 211,
    "align": "center"
  },
  "tambon": {
    "page": 1,
    "x": 245.7,
    "y": 236.1,
    "size": 16,
    "max": 133,
    "cx": 312.2,
    "align": "center"
  },
  "postcode": {
    "page": 1,
    "x": 139.7,
    "y": 257.2,
    "size": 16,
    "max": 97,
    "cx": 188.2,
    "align": "center"
  },
  "tel": {
    "page": 1,
    "x": 301.1,
    "y": 257.2,
    "size": 16,
    "max": 135,
    "cx": 368.6,
    "align": "center"
  },
  "loanRange": {
    "page": 1,
    "x": 490.6,
    "y": 302.1,
    "size": 16,
    "max": 33
  },
  "loanDate": {
    "page": 1,
    "x": 131.9,
    "y": 323,
    "size": 16,
    "max": 51
  },
  "amount": {
    "page": 1,
    "x": 229.9,
    "y": 323,
    "size": 16,
    "max": 74,
    "cx": 266.9,
    "align": "center"
  },
  "amountText": {
    "page": 1,
    "x": 329.9,
    "y": 323,
    "size": 15,
    "max": 185,
    "cx": 422.4,
    "align": "center"
  },
  "shares": {
    "page": 1,
    "x": 362.2,
    "y": 347,
    "size": 16,
    "max": 53,
    "cx": 388.7,
    "align": "center"
  },
  "shareBaht": {
    "page": 1,
    "x": 101.1,
    "y": 367.9,
    "size": 16,
    "max": 97,
    "cx": 149.6,
    "align": "center"
  },
  "shareBahtText": {
    "page": 1,
    "x": 225,
    "y": 367.9,
    "size": 15,
    "max": 208,
    "cx": 329,
    "align": "center"
  },
  "nameParen": {
    "page": 1,
    "cx": 419.8,
    "y": 595.6,
    "size": 16,
    "max": 167,
    "align": "center"
  },
  "baseDY": -11
};
